Code review exercise
wolox-training/sa-code-review pull request #1
Opened 2018-03-20 17:48 UTC by alebian

2018-05-11 04:07 UTC, petaalcala requested changes

2018-05-11 04:07 UTC, petaalcala commented on app/background/find_featured_posts.rb
> +      likes = post.likes.where('created_at > ?', 5.days.ago)
I'm thinking this will make N+1 queries, did you try using `Group by` using Post model?
I neved used it, but I'm pretty sure that will be more efficient.

http://guides.rubyonrails.org/active_record_querying.html#group

2018-05-11 04:07 UTC, petaalcala commented on app/background/update_like_count.rb
> +    post.update(like_count: Like.where(post: post).count)
This will not work, you should send the ID of the post to the worker, you can't send instances.

In addition, this worker can be replaced with a counter cache in the model Post. Did you tried it?
http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +      redirect_to @post, notice: 'Post was successfully created.'
We should use I18n here for the message, did you used it anytime?
http://guides.rubyonrails.org/i18n.html

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +      redirect_to @post, notice: 'Post was successfully updated.'
Like before, I18n here.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +      redirect_to @post, notice: 'Post was successfully updated.'
In addition to this, you should use the `if modifier` here.
Here is the link: https://www.tutorialspoint.com/ruby/ruby_if_else.htm
for example:
```
return redirect_to @post, notice: I18n.t('....') if @post.update(post_params)
render :edit
```

2018-05-11 04:07 UTC, petaalcala commented on app/background/find_featured_posts.rb
> +        post.update(featured: true)
You can use the `if modifier here`
The link is here: https://www.tutorialspoint.com/ruby/ruby_if_else.htm

ie:
```
return post.update(featured: true) if likes.size >= 5
post.update(featured: false)

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +    @post.destroy
We are not cheking here about the destroy success.
I think we should check for that before redirecting to anywhere.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +  def like
We should use "restful" controllers here.
Creating a LikesController, with the create method will be the right thing, and not here as a endpoint of the PostsController
Then, with the addition of the counter cache, the `UpdateLikeCount` will be erased.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +    FindFeaturedPosts.perform_async
I think this Job could be replaced with a scope of the Post Model, who search for post with more than 5 likes created after 5 days ago, remember that you should have a counter cache.
i.e: `Post.where(like_count > 5).where(created_at > ?, 5.days.ago)`
Also, you should constantize both numbers, maybe in the future a featured post is one who has 10 likes and it was created only today.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +      if User.exists? params[:user]
I think we should have at the start of the index function `@posts = Post.all.order(created_at: :desc)`
And then check for the existance of the user.
i.e: 
```
@posts = Post.all.order(created_at: :desc)
```
and then check for the existance of user:
```
@posts = @posts.where(user_id: params[:user]) if params[:user].present?
```
and finally render the index, if `@posts` is empty, it will render a empty list

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/repositories_controller.rb
> +class RepositoriesController < ApplicationController
If we only returns jsons here, this should inherit from `ApiController`

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/github.rb
> +  BASE_URL = "https://api.github.com"
Why not constantize this and also add to the secrets?

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/users_controller.rb
> +      redirect_to @user, notice: 'User was successfully updated.'
Use I18n here for translations of the notice.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/users_controller.rb
> +    user.update(twitter_id: params[:twitter_id], twitter_token: params[:twitter_token])
We are assuming here that the update didn't have any errors.
I think we should do something like:
```
return head: :ok if user.update(....)
return user.errors
```

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/twitter.rb
> +    HTTParty.get(URL + '/statuses/user_timeline?user_id=' + user.twitter_id + '&token=' + @token).body
We can use here HTTParty params helper, it's pretty simple.
Look at the example in:  https://github.com/jnunemaker/httparty, in the initialize method.
Using the `query` parameter.

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/weather_api.rb
> +  BASE = 'http://api.openweathermap.org/data/2.5'
We should constantize this and add them to secrets.

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/twitter.rb
> +  URL = 'https://api.twitter.com/1.1'
Why not constantize this and add them to secrets?

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/weather_controller.rb
> +    response =  WeatherApi.new.temp(params[:city])
Why not using `params.permit` here?

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/weather_controller.rb
> +      render json: { error: 'There was a problem' }, status: :bad_request
Why not adding a method here or better in the father class, which do something like:
```
def render_bad_request
  render json: { error: I18n.t('...') }, status: :bad_request
end
```
also, I think we should add a helper for rendering the response, remember to keep skinny controllers.
I know that does not exists any `Weather` model, but maybe we can add anything to handle the response and internally prepare a json to be rendered.

Then here you only need to do something like:
```
return render_bad_request if response.status_code != :ok
render json: WeatherHelperClass.render_json(response)
```

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/weather_controller.rb
> +class WeatherController < ApplicationController
We should change this to be an API, this only returns jsons.

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/twitter.rb
> +    HTTParty.get(URL + '/statuses/user_timeline?user_id=' + user.twitter_id + '&token=' + @token).body
Also we can constantize the other part of the url `/statuses/user_timeline`

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/weather_api.rb
> +      BASE + "/weather?q=#{city}&appid=" + KEY + "&units=metric"
Just like the other weather api, we should constnatize the URLS and also the helper for query creation is really good.

2018-05-11 04:07 UTC, petaalcala commented on app/third_party/weather_api.rb
> +class WeatherApi
We use to store the integrations with other services in `app/services/`.
For example, `app/services/weather_api.rb`

2018-05-11 04:07 UTC, petaalcala commented on config/routes.rb
> +  get 'repositories/github', to: 'repositories#github'
We should do a resource here, like with `users`.
Maybe this fine:
```
resources :repositories do
  get 'github'
  get 'github_gists'
end
```

2018-05-11 04:07 UTC, petaalcala commented on config/routes.rb
> +  get 'weather/temperature', to: 'weather#temperature'
Just like before, use resources for weather

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/users_controller.rb
> +    render json: { timeline: Twitter.new(User.find(params[:id])).timeline }
I think we should make a serializer for Twitter model, with `ActiveModelSerializers::Model`
https://github.com/rails-api/active_model_serializers/tree/0-10-stable#high-level-behavior

2018-05-11 04:07 UTC, petaalcala commented on Gemfile
> +gem 'httparty'
We should lock the version of the gem.
This is really easy, take a look here:
http://bundler.io/v1.5/gemfile.html

2018-05-11 04:07 UTC, petaalcala commented on spec/models/user_spec.rb
> +  describe 'case sensitive email' do
We are used to use `context` instead of `describe`

2018-05-11 04:07 UTC, petaalcala commented on spec/models/user_spec.rb
> +    let!(:user) { User.create(email: 'test@test.com', password: '123123123') }
Why we are not using factory-girl/bot here?
That is a really nice gem for mocking models.
It's really easy to use it.
https://github.com/thoughtbot/factory_bot

2018-05-11 04:07 UTC, petaalcala commented on spec/background/find_featured_posts_spec.rb
> +    let!(:likes) do
Using factory bot is really nice, we can do something like:
`FactoryBot.create_list(:like, n)`, being `n` the amount of elements.

2018-05-11 04:07 UTC, petaalcala commented on app/controllers/posts_controller.rb
> +    FindFeaturedPosts.perform_async
Also, here, you are doing this asyncronic, and the result will not be ready at the time you execute the next line.

2018-05-11 04:07 UTC, petaalcala commented on spec/controllers/weather_controller_spec.rb
> +RSpec.describe WeatherController, type: :controller do
This is not needed, you can just make something like `describe WeatherController`

2018-05-11 04:07 UTC, petaalcala commented on spec/controllers/weather_controller_spec.rb
> +      get :temperature, params: { city: :london }
You can make something like:
`let(:subject) { get :temperature, params: params }`
And then, in each place, define `params` like: `let!(:params) { { city: :london } }

This will help to do not repeat code in specs.

2018-05-11 04:07 UTC, petaalcala commented on config/initializers/devise.rb
> +  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
Why not constantize this in secrets?

2018-05-11 04:07 UTC, santyalcala commented on app/background/find_featured_posts.rb
> +      likes = post.likes.where('created_at > ?', 5.days.ago)
Also I'm not pretty sure about the usefulness if this worker, I know that saving the featured value on the DB is more efficient than calculating every time you want, like maybe adding a method to `Post`, where you can calculate if it is featured.
But doing it with a Worker, I'm not pretty sure that is useful for now, you are only using this in one endpoint where you can replace this with only a query.

2018-09-05 14:19 UTC, alebian commented
@santyalcala @icoluccio @mishuagopian @hdf1986 can we close this?

2018-09-05 14:21 UTC, closed without merging